# Generated by Django 3.1.5 on 2021-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('Reg_deadline', models.DateField()),
                ('deadline_time', models.TimeField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
