# Generated by Django 3.1.5 on 2021-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Checked', models.CharField(default='Some', max_length=1000)),
                ('Reg_type', models.CharField(choices=[('I', 'Individual'), ('G', 'Group')], max_length=30)),
                ('No_of', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
